<?xml version="1.0" ?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>object_detection</name>
    <version>0.0.0</version>
    <description>TODO</description>

    <maintainer email="mizaelmorales321@gmail.com">Mizael Morales</maintainer>

    <license>TODO</license>

    <!-- we need to build this shim pkg before any other Rust nodes! -->
    <build_depend>custom_interfaces_shim</build_depend>

    <export>
        <build_type>ament_cargo</build_type>
    </export>
</package>
